### PR TITLE
Issue #9

### PR DESCRIPTION
**Pull request by shikhar13012001**
# Description

Background property of the image has been made transparent and the hence rounded image is obtained.

Fixes #(9)

## Type of change 

- [x] Bug fix (non-breaking change which fixes an issue)
 

## Have you tested your changes
Made a test on multiple images and noted the difference with and without the change in code.

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by errorinc0de — CHANGES_REQUESTED** [review]
Download is working fine, You can retain the previous property for background.
@shikhar13012001

**Comment by shikhar13012001** [comment]
kind sir, could you please tell how it is  expected , I mean opacity of background is now 0 which makes the GDSC logo show it's background.

**Comment by errorinc0de** [comment]
I have updated the previous comment, please refer to that

**Comment by shikhar13012001** [comment]
#### sorry to disturb again sir but I needed a confirmation if this is final expected (this is made in figma). Thank you

**Comment by errorinc0de** [comment]
Looks cool!

**Comment by shikhar13012001** [comment]
### Sir I have added the round corner property to the badge please verify the PR and let me know if you want any changes.
### Thankyou
## Demo

**Review by errorinc0de — APPROVED** [review]

**Comment by errorinc0de** [comment]
Good job!
The badge looks nice!

**Comment by shikhar13012001** [comment]
> Good job! The badge looks nice!

Thank you Sir, Learnt a whole new lib with this ,Could you also add hacktober-accepted label :)

**Pull request merged**
