### PR TITLE
Added icon to the website

### LINKED ISSUE #3: Add gdsc logo to website icon..
## Suggest an improvement for a script
Add GDSC logo to website icon

## Do you want to work on this?
- [ ] yes
- [ ] no

### PR DESCRIPTION
**Pull request by codenarocode**
# Description

Added icon to the website.
Fixes #3

### CODE REVIEW

**Comment by codenarocode** [comment]
Thanx @errorinc0de  for assigning the issue to me. I have added  icon to the website .Please take a look and merge my PR

**Review by errorinc0de — CHANGES_REQUESTED** [review]
Add an icon of the developer student club logo in general, not the club specific one

**Comment by codenarocode** [comment]
I see only that logo everywhere .What are you taking about?

**Comment by codenarocode** [comment]
@errorinc0de  are u talking about this one? https://pbs.twimg.com/profile_images/1126128072523231232/GxX-zWIR_400x400.jpg

**Comment by errorinc0de** [comment]
Yes, @codenarocode something similar to that.

**Comment by codenarocode** [comment]
@errorinc0de added a circular logo

**Review by errorinc0de — APPROVED** [review]

**Pull request merged**
